# Generated by Django 5.2.6 on 2025-11-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_verification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('message', models.TextField(blank=True, null=True)),
                ('sender', models.CharField(default='antony.muchiri@cema.africa', max_length=255)),
                ('recipient', models.TextField(help_text='Reciever')),
                ('category', models.CharField(default='other', max_length=50)),
                ('status', models.CharField(choices=[('initial', 'Initial'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='initial', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
