# Generated by Django 5.2.6 on 2025-11-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='last_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
