# Generated by Django 5.2.6 on 2025-11-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_emaillog_last_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='sender',
            field=models.CharField(default='hbtap@uonbi.ac.ke', max_length=255),
        ),
    ]
