# Generated by Django 6.0.3 on 2026-03-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_emaillog_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('secretariate', 'Secretariate'), ('content_manager', 'Content Manager'), ('user', 'User'), ('swg', 'SWG')], default='user', max_length=20),
        ),
    ]
