# Generated by Django 6.0.3 on 2026-03-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('secretariat', 'Secretariat'), ('content_manager', 'Content Manager'), ('user', 'User'), ('swg', 'SWG')], default='user', max_length=20),
        ),
    ]
