# Generated by Django 6.0.3 on 2026-03-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionproposal',
            name='rescore_open',
            field=models.BooleanField(default=False),
        ),
    ]
