# Generated by Django 6.0.3 on 2026-03-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_interventionproposal_rescore_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
