# Generated by Django 6.0.3 on 2026-03-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_contactsubmission_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='organization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
