# Generated by Django 6.0.3 on 2026-03-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_contactsubmission_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
