# Generated by Django 6.0.3 on 2026-03-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_last_failed_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='sender',
            field=models.CharField(default='antony.muchiri@cema.africa', max_length=255),
        ),
    ]
