# Generated by Django 6.0.3 on 2026-03-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_emaillog_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='sender',
            field=models.CharField(default='hbtap@uonbi.ac.ke', max_length=255),
        ),
    ]
