# Generated by Django 6.0.3 on 2026-04-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_emaillog_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='sender',
            field=models.CharField(default='antony.muchiri@cema.africa', max_length=255),
        ),
    ]
