# Generated by Django 6.0.3 on 2026-04-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_emaillog_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('secretariat', 'Secretariat'), ('content_manager', 'Content Manager'), ('user', 'User'), ('swg', 'SWG'), ('panel', 'Panel')], default='user', max_length=20),
        ),
    ]
