# Generated by Django 6.0.3 on 2026-03-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectiontool',
            name='morbidity_score',
        ),
        migrations.RemoveField(
            model_name='selectiontool',
            name='mortality_score',
        ),
    ]
