# Generated by Django 6.0.3 on 2026-03-06 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_selectiontool_morbidity_score_and_more'),
        ('users', '0005_alter_emaillog_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemcategory',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='systemcategory',
            old_name='system_category',
            new_name='name',
        ),
        migrations.AddField(
            model_name='interventionsystemcategory',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interventionsystemcategory',
            name='system_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='app.systemcategory'),
        ),
        migrations.AlterField(
            model_name='systemcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='interventionscore',
            unique_together={('reviewer', 'intervention', 'criteria')},
        ),
    ]
