# Generated by Django 6.0.3 on 2026-03-12 05:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_systemcategory_options_and_more'),
        ('users', '0006_customuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brief_info', models.TextField(blank=True, null=True)),
                ('clinical_effectiveness', models.TextField(blank=True, null=True)),
                ('burden_of_disease', models.TextField(blank=True, null=True)),
                ('bod_type', models.CharField(blank=True, choices=[('DALY', 'DALY'), ('QALY', 'QALY'), ('PREVALENCE', 'Prevalence'), ('INCIDENCE', 'Incidence')], max_length=20, null=True)),
                ('population', models.TextField(blank=True, null=True)),
                ('equity', models.TextField(blank=True, null=True)),
                ('cost_effectiveness', models.TextField(blank=True, null=True)),
                ('budget_impact_affordability', models.TextField(blank=True, null=True)),
                ('feasibility_of_implementation', models.TextField(blank=True, null=True)),
                ('catastrophic_health_expenditure', models.TextField(blank=True, null=True)),
                ('access_to_healthcare', models.TextField(blank=True, null=True)),
                ('congruence_with_health_priorities', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_information', to='users.interventionproposal')),
                ('system_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criteria_information', to='app.systemcategory')),
            ],
            options={
                'verbose_name': 'Criteria Information',
                'verbose_name_plural': 'Criteria Information',
                'ordering': ['-created_at'],
            },
        ),
    ]
