# Generated by Django 6.0.3 on 2026-03-12 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_criteriainformation'),
        ('users', '0006_customuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteriainformation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='criteriainformation',
            index=models.Index(fields=['intervention'], name='idx_criteria_intervention'),
        ),
    ]
