# Generated by Django 6.0.3 on 2026-03-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_criteriainformation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriainformation',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
