# Generated by Django 6.0.3 on 2026-03-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_criteriainformation_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteriainformation',
            name='system_category',
        ),
        migrations.RemoveField(
            model_name='criteriainformation',
            name='title',
        ),
        migrations.AddField(
            model_name='criteriainformation',
            name='system_categories',
            field=models.ManyToManyField(blank=True, related_name='criteria_information', to='app.systemcategory'),
        ),
    ]
