# Generated by Django 6.0.3 on 2026-03-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_criteriainformation_system_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteriainformation',
            name='system_categories',
        ),
    ]
