# Generated by Django 6.0.3 on 2026-03-19 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_criteriainformation_system_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionscore',
            name='is_rescored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interventionscore',
            name='rescored_by',
            field=models.ForeignKey(blank=True, help_text='The reviewer who applied the rescore.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescored_scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
