# Generated by Django 6.0.3 on 2026-03-23 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_interventionscore_is_rescored_and_more'),
        ('users', '0008_interventionproposal_rescore_open'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interventionscore',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='interventionscore',
            index=models.Index(fields=['reviewer'], name='app_interve_reviewe_df59b3_idx'),
        ),
        migrations.AddIndex(
            model_name='interventionscore',
            index=models.Index(fields=['intervention'], name='app_interve_interve_b71e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='interventionscore',
            index=models.Index(fields=['criteria'], name='app_interve_criteri_95e036_idx'),
        ),
        migrations.AddIndex(
            model_name='interventionscore',
            index=models.Index(fields=['created_at'], name='app_interve_created_081ade_idx'),
        ),
    ]
