# Generated by Django 6.0.3 on 2026-03-24 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_interventionscore_options_and_more'),
        ('users', '0008_interventionproposal_rescore_open'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InterventionStatusUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ON_REVIEW', 'On Review'), ('DECIDED', 'Decided'), ('CLOSED', 'Closed'), ('COMPLETE', 'Complete')], default='PENDING', max_length=20)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, help_text='Plain-language feedback visible to the submitter.')),
                ('justification', models.TextField(blank=True, help_text='Internal justification supporting the status or decision.')),
                ('additional_info', models.TextField(blank=True, help_text='More info supporting the decision.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.ForeignKey(blank=True, help_text='Formal HTA decision once reached.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_updates', to='app.decisiontype')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='users.interventionproposal')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervention_status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['intervention'], name='idx_status_intervention'), models.Index(fields=['status'], name='idx_status_status'), models.Index(fields=['decision_date'], name='idx_status_decision_date')],
            },
        ),
    ]
