# Generated by Django 6.0.3 on 2026-03-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_decisiontype_interventionstatusupdate'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='interventionstatusupdate',
            name='idx_status_status',
        ),
        migrations.RemoveField(
            model_name='interventionstatusupdate',
            name='status',
        ),
    ]
