# Generated by Django 6.0.3 on 2026-03-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_interventionstatusupdate_idx_status_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interventionstatusupdate',
            name='justification',
        ),
    ]
