# Generated by Django 6.0.3 on 2026-04-20 06:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_criteriaappraisaltool_criteriaappraisalscore'),
        ('users', '0014_alter_emaillog_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(help_text='Email subject line. You may use {{ decision_type }}, {{ submitter_name }}, etc.', max_length=255)),
                ('template', models.TextField(help_text='Full HTML email body. Available variables: {{ submitter_name }}, {{ submitter_email }}, {{ decision_type }}, {{ decision_date }}, {{ feedback }}, {{ org_name }}, {{ org_email }}, {{ current_year }}.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feedback Category',
                'verbose_name_plural': 'Feedback Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackEmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_sent', models.TextField()),
                ('message_sent', models.TextField()),
                ('recipient', models.EmailField(max_length=254)),
                ('sender', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('initial', 'Initial'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='initial', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_logs', to='app.feedbackcategory')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_email_logs', to='users.interventionproposal')),
                ('sent_by', models.ForeignKey(blank=True, help_text='Staff member who triggered the send.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_emails_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['intervention'], name='idx_femail_intervention'), models.Index(fields=['category'], name='idx_femail_category'), models.Index(fields=['status'], name='idx_femail_status')],
            },
        ),
    ]
