# Generated by Django 6.0.3 on 2026-04-23 11:15

import app.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_feedbackcategory_feedbackemaillog'),
        ('users', '0015_alter_emaillog_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalCriteriaEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brief_info', models.TextField(blank=True, null=True)),
                ('mortality_score', models.IntegerField(blank=True, null=True)),
                ('morbidity_score', models.IntegerField(blank=True, null=True)),
                ('clinical_effectiveness', models.TextField(blank=True, null=True)),
                ('population', models.TextField(blank=True, null=True)),
                ('equity', models.TextField(blank=True, null=True)),
                ('cost_effectiveness', models.TextField(blank=True, null=True)),
                ('budget_impact_affordability', models.TextField(blank=True, null=True)),
                ('catastrophic_health_expenditure', models.TextField(blank=True, null=True)),
                ('feasibility_of_implementation', models.TextField(blank=True, null=True)),
                ('access_to_healthcare', models.TextField(blank=True, null=True)),
                ('congruence_with_health_priorities', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_evidence_created', to=settings.AUTH_USER_MODEL)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_evidence', to='users.interventionproposal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalEvidenceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=app.models.evidence_document_path)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.appraisalcriteriaevidence')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalEvidenceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=app.models.evidence_image_path)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.appraisalcriteriaevidence')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_images_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
