# Generated by Django 6.0.3 on 2026-04-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_appraisalcriteriaevidence_appraisalevidencedocument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisalcriteriaevidence',
            name='morbidity_score',
        ),
        migrations.RemoveField(
            model_name='appraisalcriteriaevidence',
            name='mortality_score',
        ),
        migrations.AddField(
            model_name='appraisalcriteriaevidence',
            name='burden_of_disease_morbidity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisalcriteriaevidence',
            name='burden_of_disease_mortality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisalcriteriaevidence',
            name='quality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisalcriteriaevidence',
            name='safety',
            field=models.TextField(blank=True, null=True),
        ),
    ]
