# Generated by Django 6.0.3 on 2026-04-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_appraisalcriteriaevidence_morbidity_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteriaappraisaltool',
            name='scores',
        ),
        migrations.AddField(
            model_name='criteriaappraisaltool',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criteriaappraisaltool',
            name='scoring_approach',
            field=models.TextField(blank=True),
        ),
    ]
