# Generated by Django 6.0.3 on 2026-05-04 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_criteriaappraisaltool_scores_and_more'),
        ('users', '0016_alter_customuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionstatusupdate',
            name='move_to_panel',
            field=models.BooleanField(default=False, help_text='Mark intervention to move to panel review.'),
        ),
        migrations.AddIndex(
            model_name='interventionstatusupdate',
            index=models.Index(fields=['move_to_panel'], name='idx_status_move_to_panel'),
        ),
    ]
