# Generated by Django 6.0.3 on 2026-05-05 07:51

import app.core.consts
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_interventionstatusupdate_move_to_panel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionstatusupdate',
            name='decision',
            field=models.ForeignKey(blank=True, default=app.core.consts.get_pending_decision, help_text='Formal HTA decision once reached.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_updates', to='app.decisiontype'),
        ),
    ]
