# Generated by Django 6.0.3 on 2026-05-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_activity_subactivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subactivity',
            name='hta_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
