# Generated by Django 6.0.3 on 2026-06-02 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_activity_urgency_alter_subactivity_urgency'),
        ('users', '0016_alter_customuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionScoringWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('panel', 'Panel (SWG)'), ('appraisal', 'Appraisal')], db_index=True, max_length=20)),
                ('starts_at', models.DateTimeField(help_text='When scoring opens for reviewers.')),
                ('ends_at', models.DateTimeField(help_text='When the scoring window closes.')),
                ('submission_delay_minutes', models.PositiveIntegerField(default=2, help_text='Grace period in minutes after ends_at during which late submissions are still accepted.')),
                ('is_active', models.BooleanField(default=True, help_text='Set false to disable this window regardless of dates.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoring_windows_created', to=settings.AUTH_USER_MODEL)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_windows', to='users.interventionproposal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoring_windows_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['intervention', 'level'], name='app_interve_interve_d6b2f8_idx'), models.Index(fields=['starts_at'], name='app_interve_starts__e94523_idx'), models.Index(fields=['ends_at'], name='app_interve_ends_at_155d4c_idx'), models.Index(fields=['is_active'], name='app_interve_is_acti_eb2cb5_idx')],
                'unique_together': {('intervention', 'level')},
            },
        ),
    ]
