# Generated by Django 5.2.6 on 2025-10-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='type',
            new_name='feedback_type',
        ),
    ]
