# Generated by Django 5.2.6 on 2025-10-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_type_feedback_feedback_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_type',
        ),
    ]
