# Generated by Django 5.2.6 on 2025-10-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_feedback_feedback_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
