# Generated by Django 6.0.3 on 2026-03-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_eventdocument_eventimage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='non_empty_message_content',
        ),
    ]
