# Generated by Django 6.0.3 on 2026-06-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_message_non_empty_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='send_email_alert',
            field=models.BooleanField(default=False, help_text='If true, send an alert email to assigned users.'),
        ),
    ]
